-- AlterTable
ALTER TABLE `FileCoverage` ADD COLUMN `coveredElements` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `elements` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `PackageCoverage` ADD COLUMN `coveredElements` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `elements` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Test` ADD COLUMN `coveredElements` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `elements` INTEGER NOT NULL DEFAULT 0;
